PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS Auteur(
   id_Auteur INTEGER PRIMARY KEY,
   nom_auteur VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Livre(
   id_livre INTEGER PRIMARY KEY,
   titre VARCHAR(100) UNIQUE NOT NULL,
   id_Auteur INTEGER,
   FOREIGN KEY(id_Auteur) REFERENCES Auteur(id_Auteur)
);

CREATE TABLE IF NOT EXISTS Note(
   id_note INTEGER PRIMARY KEY AUTOINCREMENT,
   titre VARCHAR(100) UNIQUE NOT NULL,
   texte VARCHAR(500),
   date_creation DATETIME DEFAULT CURRENT_TIMESTAMP,
   supprimee BOOLEAN DEFAULT 0,
   id_livre INTEGER,
   FOREIGN KEY(id_livre) REFERENCES Livre(id_livre)
);

CREATE TABLE IF NOT EXISTS Historique(
   id_historique INTEGER PRIMARY KEY AUTOINCREMENT,
   mot_cle VARCHAR(100) UNIQUE NOT NULL,
   date_historique DATETIME DEFAULT CURRENT_TIMESTAMP
);


